version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: db
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - smart-aviation-web-application-network

  smart-aviation-app:
    build: .
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - smart-aviation-web-application-network

# Volumes
volumes:
  mysql-database-data-volume:

networks:
  smart-aviation-web-application-network: