spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/db'
    username: user
    password: user
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        search:
          backend:
            directory:
              root: target/search-index
            analysis:
              configurer: com.sv.smartaviation.config.MyLuceneAnalysisConfigurer
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        connection:
          isolation: '2'
        check_nullability: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  jackson:
    time-zone: UTC
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: 'false'


app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 1800000 # 30mins
  jwtRefreshExpirationInMs: 3600000 # 1hr
  cors:
    allowedOrigins: http://localhost:3000/

springdoc:
  packagesToScan: com.sv.smartaviation

logging:
  level:
    org.hibernate.type: trace
    com.sv.smartaviation: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

api:
  airlabs:
    url: https://skyscanner44.p.rapidapi.com
    host: skyscanner44.p.rapidapi.com
    #    key: ${AIR_LABS_KEY}
    key: ytXEqjajXYmsh5qUKlYWDuuTot1fp18ZX42jsnKFioZ4Sk2kMI
    debug: true

server:
  port: 9000
