spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/db'
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        connection:
          isolation: '2'
        check_nullability: true
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  packagesToScan: com.sv.smartaviation

logging:
  level:
    org.hibernate.type: trace
    com.sv.smartaviation: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

api:
  airlabs:
    url: https://airlabs.co/api/v9
    #    key: ${AIR_LABS_KEY}
    key: 6df9ff4a-c629-41e6-a0a0-a207d214e380
    debug: true

server:
  port: 9000
